const constants = {
  UPDATE_AUTHORS_SUCCESS: 'UPDATE_AUTHORS_SUCCESS',
  UPDATE_AUTHORS_FAILURE: 'UPDATE_AUTHORS_FAILURE',
  UPDATE_FEATURED_SUCCESS: 'UPDATE_FEATURED_SUCCESS',
  UPDATE_FEATURED_FAILURE: 'UPDATE_FEATURED_FAILURE',
  UPDATE_POPULAR_SUCCESS: 'UPDATE_POPULAR_SUCCESS',
  UPDATE_POPULAR_FAILURE: 'UPDATE_POPULAR_FAILURE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',
  USER_SIGNUP_STARTED: 'USER_SIGNUP_STARTED',
  MODAL_SHOW: 'MODAL_SHOW',
  MODAL_CLOSE: 'MODAL_CLOSE',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  FETCH_ARTICLE_START: 'FETCH_ARTICLE_START',
  FETCH_ARTICLE_SUCCESS: 'FETCH_ARTICLE_SUCCESS',
  FETCH_ARTICLE_FAIL: 'FETCH_ARTICLE_FAIL',
  SET_HERO_CONTENT: 'SET_HERO_CONTENT',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
};

export default constants;
