export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
export const USER_SIGNUP_STARTED = 'USER_SIGNUP_STARTED';
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
